### ISSUE TITLE
Group related sass folders inside a modules folder

### ISSUE THREAD

**Issue by jeroenransijn** [edgargressie/harbour#5]
Grouping `base`, `components`, `layout`, `pages` and `vendor-overrides` might have the benefit of a better workflow for certain users. The main argument being that files outside of this folder require only a one-time effort to set up. The files inside `modules` require continuous development.  Developers with a folder oriented workflow might benefit from such a separation of concerns. On the other side of the argument is that it will not necessarily be an enhancement, but an additional abstraction, which increases the complexity of the file structure.

If this enhancement is something to be incorporated into the main project the following steps should be taken:
- decide on the the name of the folder the sub folders will be put in E.G. `modules/theme` 
- decide which folders will be grouped into the new folder
- work out the feature

Leave your suggestions and feedback inside this thread.

**Comment by bartvandebiezen** [comment]
I agree it is increasing the complexity of the file structure. I vote against placing these folders in 'modules'.

**Comment by edgargressie** [comment]
I agree with @bartvandebiezen
