### ISSUE TITLE
Add 2 utilities for mixing colours with white and black

### ISSUE THREAD

**Issue by jeroenransijn** [edgargressie/harbour#7]
Inside Sass there is a `mix` function which takes 3 arguments `mix($color-1, $color-2, [$weight])`. Often used to mix a colour with black or white. However it is hard to know what the `$weight` does to the two colours. [Inside the Compass library](http://compass-style.org/reference/compass/helpers/colors/) there are two functions who take care of this confusion: `shade` and `tint`. Each function would get it's own file, I would like to propose using these two colour functions as:

## Shade
```
// Mixes the $color with a certain percentage of black:
// 0 is original colour and 100 all black
shade($color, $percentage)
```

## Tint
```
// Mixes the $color with a certain percentage of white:
// 0 is original colour and 100 is all white
tint($color, $percentage)
```

[Overview of all colour functions in Sass and Compass](http://jackiebalzer.com/color)

**Comment by bartvandebiezen** [comment]
Why not include Compass?

**Comment by bartvandebiezen** [comment]
Probably that would be to big. Vote for adding shade and tint :+1:

**Comment by edgargressie** [comment]
Already part of Bourbon (http://bourbon.io/docs/#tint-shade)
